{
  "openapi": "3.1.0",
  "info": {
    "title": "Senior Project",
    "summary": "This is an API for a small hometown movie theater",
    "description": "This is created for a senior project for an applied technology degree from BYU-Idaho. It is built by Katrina Lyman with the needs of San Juan Theater in mind and under the supervision of Professor Blaine Robertson.",
    "contact": {
      "name": "Katrina Lyman",
      "email": "lymankatrina@gmail.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://sanjuantheater.onrender.com",
      "description": "Production server"
    },
    {
      "url": "http://localhost:8080",
      "description": "Development server"
    }
  ],
  "paths": {
    "/profile": {
      "get": {
        "tags": ["Authentication"],
        "summary": "Get Profile",
        "description": "This will return the authenticated user profile information for the current authenticated user.",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/users/new": {
      "post": {
        "tags": ["Users"],
        "summary": "Create a new user",
        "description": "Enter the required information to add a new user to the users collection",
        "responses": {
          "201": {
            "description": "New User created",
            "content": {
              "application/json": {
                "example": {
                  "_id": "uniqueId",
                  "firstName": "Horatio",
                  "lastName": "Crunch",
                  "userName": "Horatio Crunch",
                  "phone": "888-555-1234",
                  "email": "capncrunch@example.com",
                  "isAdmin": true
                }
              }
            }
          },
          "400": {
            "description": "Error message"
          },
          "403": {
            "description": "Access denied"
          },
          "412": {
            "description": "Precondition Failed"
          },
          "500": {
            "description": "Failed to create a new user"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "firstName": "Horatio",
                "lastName": "Crunch",
                "userName": "Horatio Crunch",
                "phone": "888-555-1234",
                "email": "capncrunch@example.com",
                "isAdmin": true
              }
            }
          }
        }
      }
    },
    "/users/all": {
      "get": {
        "tags": ["Users"],
        "summary": "Get all users",
        "description": "Get an array of all users in the collection",
        "responses": {
          "200": {
            "description": "A list of users.",
            "content": {
              "application/json": {
                "example": {
                  "_id": "uniqueId",
                  "firstName": "Horatio",
                  "lastName": "Crunch",
                  "userName": "Horatio Crunch",
                  "phone": "888-555-1234",
                  "email": "capncrunch@example.com",
                  "isAdmin": true
                }
              }
            }
          },
          "403": {
            "description": "Access denied"
          },
          "500": {
            "description": "Error message"
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "tags": ["Users"],
        "summary": "Get a user by ID",
        "description": "This will return a single user by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "example": {
                  "_id": "uniqueId",
                  "firstName": "Horatio",
                  "lastName": "Crunch",
                  "userName": "Horatio Crunch",
                  "phone": "888-555-1234",
                  "email": "capncrunch@example.com",
                  "isAdmin": true
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Access denied"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Error message"
          }
        }
      }
    },
    "/users/email/{email}": {
      "get": {
        "tags": ["Users"],
        "summary": "Get a user by Email",
        "description": "This will return a single user by Email",
        "parameters": [
          {
            "name": "email",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "example": {
                  "_id": "uniqueId",
                  "firstName": "Horatio",
                  "lastName": "Crunch",
                  "userName": "Horatio Crunch",
                  "phone": "888-555-1234",
                  "email": "capncrunch@example.com",
                  "isAdmin": true
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Access denied"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Error message"
          }
        }
      }
    },
    "/users/update/{id}": {
      "put": {
        "tags": ["Users"],
        "summary": "Update a user by ID",
        "description": "This will update a single user by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully updated",
            "content": {
              "application/json": {
                "example": {
                  "_id": "uniqueId",
                  "firstName": "Horatio",
                  "lastName": "Crunch",
                  "userName": "Horatio Crunch",
                  "phone": "888-555-1234",
                  "email": "capncrunch@example.com",
                  "isAdmin": true
                }
              }
            }
          },
          "304": {
            "description": "Not updated"
          },
          "400": {
            "description": "Error message"
          },
          "403": {
            "description": "Access denied"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "firstName": "Horatio",
                "lastName": "Crunch",
                "userName": "Horatio Crunch",
                "phone": "888-555-1234",
                "email": "capncrunch@example.com",
                "isAdmin": true
              }
            }
          }
        }
      }
    },
    "/users/delete/{id}": {
      "delete": {
        "tags": ["Users"],
        "summary": "Delete a user by ID",
        "description": "This will delete a single user by ID. This action cannot be reversed.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "202": {
            "description": "User Successfully deleted"
          },
          "400": {
            "description": "User Not Deleted"
          },
          "403": {
            "description": "Access denied"
          },
          "404": {
            "description": "User Not Found"
          },
          "500": {
            "description": "Error message"
          }
        }
      }
    },
    "/genres/new": {
      "post": {
        "tags": ["Genres"],
        "summary": "Create a new genre",
        "description": "Enter the required information to add a new genre to the genres collection",
        "responses": {
          "201": {
            "description": "New Genre created",
            "content": {
              "application/json": {
                "example": {
                  "_id": "uniqueId",
                  "genre": "Action"
                }
              }
            }
          },
          "400": {
            "description": "Error message"
          },
          "403": {
            "description": "Access denied"
          },
          "412": {
            "description": "Precondition Failed"
          },
          "500": {
            "description": "Failed to create a new genre"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "genre": "Action"
              }
            }
          }
        }
      }
    },
    "/genres/all": {
      "get": {
        "tags": ["Genres"],
        "summary": "Get all genres",
        "description": "Get an array of all movie genres in the collection",
        "responses": {
          "200": {
            "description": "A list of genres.",
            "content": {
              "application/json": {
                "example": {
                  "_id": "uniqueId",
                  "genre": "Action"
                }
              }
            }
          },
          "403": {
            "description": "Access denied"
          },
          "500": {
            "description": "Error message"
          }
        }
      }
    },
    "/genres/{id}": {
      "get": {
        "tags": ["Genres"],
        "summary": "Get a genre by ID",
        "description": "This will return a single genre by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "example": {
                  "_id": "uniqueId",
                  "genre": "Action"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Access denied"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Error message"
          }
        }
      }
    },
    "/genres/genre/{genre}": {
      "get": {
        "tags": ["Genres"],
        "summary": "Get a genre by genre name",
        "description": "This will return a single movie genre by name",
        "parameters": [
          {
            "name": "genre",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "example": {
                  "_id": "uniqueId",
                  "genre": "Action"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Access denied"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Error message"
          }
        }
      }
    },
    "/genres/update/{id}": {
      "put": {
        "tags": ["Genres"],
        "summary": "Update a genre by ID",
        "description": "This will update a single genre by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully updated",
            "content": {
              "application/json": {
                "example": {
                  "_id": "uniqueId",
                  "genre": "Action"
                }
              }
            }
          },
          "304": {
            "description": "Not updated"
          },
          "400": {
            "description": "Error message"
          },
          "403": {
            "description": "Access denied"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "genre": "Action"
              }
            }
          }
        }
      }
    },
    "/genres/delete/{id}": {
      "delete": {
        "tags": ["Genres"],
        "summary": "Delete a genre by ID",
        "description": "This will delete a single genre by ID. This action cannot be reversed.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "202": {
            "description": "Genre Successfully deleted"
          },
          "400": {
            "description": "Genre Not Deleted"
          },
          "403": {
            "description": "Access denied"
          },
          "404": {
            "description": "Genre Not Found"
          },
          "500": {
            "description": "Error message"
          }
        }
      }
    },
    "/movies/new": {
      "post": {
        "tags": ["Movies"],
        "summary": "Create a new movie",
        "description": "Enter the required information to add a new movie to the movies collection",
        "responses": {
          "201": {
            "description": "New Movie created",
            "content": {
              "application/json": {
                "example": {
                  "_id": "uniqueId",
                  "title": "The Fall Guy",
                  "tagLine": "Fall Hard",
                  "overview": "He's a stuntman, and like everyone in the stunt community, he gets blown up, shot, crashed, thrown through windows and dropped from the highest of heights, all for our entertainment. And now, fresh off an almost career-ending accident, this working-class hero has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job. What could possibly go right?",
                  "year": "2024",
                  "certification": "PG-13",
                  "releaseDate": "2024-05-03",
                  "genres": ["663e79ad68454688b10dbead", "663e7a1368454688b10dbeb2", "663e7a2f68454688b10dbeb5"],
                  "runtime": "2h 6m",
                  "imdbScore": "7.3",
                  "rottenTomatoes": "82%",
                  "fandangoAudienceScore": "86%",
                  "poster": "https://dx35vtwkllhj9.cloudfront.net/universalstudios/the-fall-guy/images/regions/us/onesheet.jpg",
                  "trailer": "https://youtu.be/j7jPnwVGdZ8",
                  "isPremier": false,
                  "startDate": "2024-05-10",
                  "endDate": "2024-05-16",
                  "isActive": true
                }
              }
            }
          },
          "400": {
            "description": "Error message"
          },
          "403": {
            "description": "Access denied"
          },
          "412": {
            "description": "Precondition Failed"
          },
          "500": {
            "description": "Failed to create a new user"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "title": "The Fall Guy",
                "tagLine": "Fall Hard",
                "overview": "He's a stuntman, and like everyone in the stunt community, he gets blown up, shot, crashed, thrown through windows and dropped from the highest of heights, all for our entertainment. And now, fresh off an almost career-ending accident, this working-class hero has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job. What could possibly go right?",
                "year": "2024",
                "certification": "PG-13",
                "releaseDate": "2024-05-03",
                "genres": ["663e79ad68454688b10dbead", "663e7a1368454688b10dbeb2", "663e7a2f68454688b10dbeb5"],
                "runtime": "2h 6m",
                "imdbScore": "7.3",
                "rottenTomatoes": "82%",
                "fandangoAudienceScore": "86%",
                "poster": "https://dx35vtwkllhj9.cloudfront.net/universalstudios/the-fall-guy/images/regions/us/onesheet.jpg",
                "trailer": "https://youtu.be/j7jPnwVGdZ8",
                "isPremier": false,
                "startDate": "2024-05-10",
                "endDate": "2024-05-16",
                "isActive": true
              }
            }
          }
        }
      }
    },
    "/movies/all": {
      "get": {
        "tags": ["Movies"],
        "summary": "Get all movies",
        "description": "Get an array of all movies in the collection",
        "responses": {
          "200": {
            "description": "A list of movies.",
            "content": {
              "application/json": {
                "example": {
                  "_id": "uniqueId",
                  "title": "The Fall Guy",
                  "tagLine": "Fall Hard",
                  "overview": "He's a stuntman, and like everyone in the stunt community, he gets blown up, shot, crashed, thrown through windows and dropped from the highest of heights, all for our entertainment. And now, fresh off an almost career-ending accident, this working-class hero has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job. What could possibly go right?",
                  "year": "2024",
                  "certification": "PG-13",
                  "releaseDate": "2024-05-03",
                  "genres": ["663e79ad68454688b10dbead", "663e7a1368454688b10dbeb2", "663e7a2f68454688b10dbeb5"],
                  "runtime": "2h 6m",
                  "imdbScore": "7.3",
                  "rottenTomatoes": "82%",
                  "fandangoAudienceScore": "86%",
                  "poster": "https://dx35vtwkllhj9.cloudfront.net/universalstudios/the-fall-guy/images/regions/us/onesheet.jpg",
                  "trailer": "https://youtu.be/j7jPnwVGdZ8",
                  "isPremier": false,
                  "startDate": "2024-05-10",
                  "endDate": "2024-05-16",
                  "isActive": true
                }
              }
            }
          },
          "403": {
            "description": "Access denied"
          },
          "500": {
            "description": "Error message"
          }
        }
      }
    },
    "/movies/nowplaying": {
      "get": {
        "tags": ["Movies"],
        "summary": "Get current movies",
        "description": "Get movies currently playing",
        "responses": {
          "200": {
            "description": "A list of current movies.",
            "content": {
              "application/json": {
                "example": {
                  "_id": "uniqueId",
                  "title": "The Fall Guy",
                  "tagLine": "Fall Hard",
                  "overview": "He's a stuntman, and like everyone in the stunt community, he gets blown up, shot, crashed, thrown through windows and dropped from the highest of heights, all for our entertainment. And now, fresh off an almost career-ending accident, this working-class hero has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job. What could possibly go right?",
                  "year": "2024",
                  "certification": "PG-13",
                  "releaseDate": "2024-05-03",
                  "genres": ["663e79ad68454688b10dbead", "663e7a1368454688b10dbeb2", "663e7a2f68454688b10dbeb5"],
                  "runtime": "2h 6m",
                  "imdbScore": "7.3",
                  "rottenTomatoes": "82%",
                  "fandangoAudienceScore": "86%",
                  "poster": "https://dx35vtwkllhj9.cloudfront.net/universalstudios/the-fall-guy/images/regions/us/onesheet.jpg",
                  "trailer": "https://youtu.be/j7jPnwVGdZ8",
                  "isPremier": false,
                  "startDate": "2024-05-10",
                  "endDate": "2024-05-16",
                  "isActive": true
                }
              }
            }
          },
          "403": {
            "description": "Access denied"
          },
          "500": {
            "description": "Error message"
          }
        }
      }
    },
    "/movies/comingSoon": {
      "get": {
        "tags": ["Movies"],
        "summary": "Get movies coming soon",
        "description": "Get movies coming soon",
        "responses": {
          "200": {
            "description": "A list of movies coming soon.",
            "content": {
              "application/json": {
                "example": {
                  "_id": "uniqueId",
                  "title": "The Fall Guy",
                  "tagLine": "Fall Hard",
                  "overview": "He's a stuntman, and like everyone in the stunt community, he gets blown up, shot, crashed, thrown through windows and dropped from the highest of heights, all for our entertainment. And now, fresh off an almost career-ending accident, this working-class hero has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job. What could possibly go right?",
                  "year": "2024",
                  "certification": "PG-13",
                  "releaseDate": "2024-05-03",
                  "genres": ["663e79ad68454688b10dbead", "663e7a1368454688b10dbeb2", "663e7a2f68454688b10dbeb5"],
                  "runtime": "2h 6m",
                  "imdbScore": "7.3",
                  "rottenTomatoes": "82%",
                  "fandangoAudienceScore": "86%",
                  "poster": "https://dx35vtwkllhj9.cloudfront.net/universalstudios/the-fall-guy/images/regions/us/onesheet.jpg",
                  "trailer": "https://youtu.be/j7jPnwVGdZ8",
                  "isPremier": false,
                  "startDate": "2024-05-10",
                  "endDate": "2024-05-16",
                  "isActive": true
                }
              }
            }
          },
          "403": {
            "description": "Access denied"
          },
          "500": {
            "description": "Error message"
          }
        }
      }
    },
    "/movies/{id}": {
      "get": {
        "tags": ["Movies"],
        "summary": "Get a movie by ID",
        "description": "This will return a single movie by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "example": {
                  "_id": "uniqueId",
                  "title": "The Fall Guy",
                  "tagLine": "Fall Hard",
                  "overview": "He's a stuntman, and like everyone in the stunt community, he gets blown up, shot, crashed, thrown through windows and dropped from the highest of heights, all for our entertainment. And now, fresh off an almost career-ending accident, this working-class hero has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job. What could possibly go right?",
                  "year": "2024",
                  "certification": "PG-13",
                  "releaseDate": "2024-05-03",
                  "genres": ["663e79ad68454688b10dbead", "663e7a1368454688b10dbeb2", "663e7a2f68454688b10dbeb5"],
                  "runtime": "2h 6m",
                  "imdbScore": "7.3",
                  "rottenTomatoes": "82%",
                  "fandangoAudienceScore": "86%",
                  "poster": "https://dx35vtwkllhj9.cloudfront.net/universalstudios/the-fall-guy/images/regions/us/onesheet.jpg",
                  "trailer": "https://youtu.be/j7jPnwVGdZ8",
                  "isPremier": false,
                  "startDate": "2024-05-10",
                  "endDate": "2024-05-16",
                  "isActive": true
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Access denied"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Error message"
          }
        }
      }
    },
    "/movies/title/{title}": {
      "get": {
        "tags": ["Movies"],
        "summary": "Get a movie by title",
        "description": "This will return a single movie by title",
        "parameters": [
          {
            "name": "title",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "example": {
                  "_id": "uniqueId",
                  "title": "The Fall Guy",
                  "tagLine": "Fall Hard",
                  "overview": "He's a stuntman, and like everyone in the stunt community, he gets blown up, shot, crashed, thrown through windows and dropped from the highest of heights, all for our entertainment. And now, fresh off an almost career-ending accident, this working-class hero has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job. What could possibly go right?",
                  "year": "2024",
                  "certification": "PG-13",
                  "releaseDate": "2024-05-03",
                  "genres": ["663e79ad68454688b10dbead", "663e7a1368454688b10dbeb2", "663e7a2f68454688b10dbeb5"],
                  "runtime": "2h 6m",
                  "imdbScore": "7.3",
                  "rottenTomatoes": "82%",
                  "fandangoAudienceScore": "86%",
                  "poster": "https://dx35vtwkllhj9.cloudfront.net/universalstudios/the-fall-guy/images/regions/us/onesheet.jpg",
                  "trailer": "https://youtu.be/j7jPnwVGdZ8",
                  "isPremier": false,
                  "startDate": "2024-05-10",
                  "endDate": "2024-05-16",
                  "isActive": true
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Access denied"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Error message"
          }
        }
      }
    },
    "/movies/update/{id}": {
      "put": {
        "tags": ["Movies"],
        "summary": "Update a movie by ID",
        "description": "This will update a single movie by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully updated"
          },
          "304": {
            "description": "Not updated"
          },
          "400": {
            "description": "Error message"
          },
          "403": {
            "description": "Access denied"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "title": "The Fall Guy",
                "tagLine": "Fall Hard",
                "overview": "He's a stuntman, and like everyone in the stunt community, he gets blown up, shot, crashed, thrown through windows and dropped from the highest of heights, all for our entertainment. And now, fresh off an almost career-ending accident, this working-class hero has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job. What could possibly go right?",
                "year": "2024",
                "certification": "PG-13",
                "releaseDate": "2024-05-03",
                "genres": ["663e79ad68454688b10dbead", "663e7a1368454688b10dbeb2", "663e7a2f68454688b10dbeb5"],
                "runtime": "2h 6m",
                "imdbScore": "7.3",
                "rottenTomatoes": "82%",
                "fandangoAudienceScore": "86%",
                "poster": "https://dx35vtwkllhj9.cloudfront.net/universalstudios/the-fall-guy/images/regions/us/onesheet.jpg",
                "trailer": "https://youtu.be/j7jPnwVGdZ8",
                "isPremier": false,
                "startDate": "2024-05-10",
                "endDate": "2024-05-16",
                "isActive": true
              }
            }
          }
        }
      }
    },
    "/movies/delete/{id}": {
      "delete": {
        "tags": ["Movies"],
        "summary": "Delete a movie by ID",
        "description": "This will delete a single movie by ID. This action cannot be reversed.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "202": {
            "description": "Movie Successfully deleted"
          },
          "400": {
            "description": "Movie Not Deleted"
          },
          "403": {
            "description": "Access denied"
          },
          "404": {
            "description": "Movie Not Found"
          },
          "500": {
            "description": "Error message"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Users": {
        "type": "object",
        "required": ["id", "firstName", "lastName", "userName", "phone", "email", "isAdmin"],
        "properties": {
          "_id": {
            "type": "string",
            "format": "objectId"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "userName": {
            "type": "string"
          },
          "phone": {
            "type": "string",
            "format": "###-###-####"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "isAdmin": {
            "type": "boolean"
          }
        }
      },
      "Movies": {
        "type": "object",
        "required": [
          "_id",
          "title",
          "tagLine",
          "overview",
          "year",
          "certification",
          "releaseDate",
          "genres",
          "runtime",
          "image",
          "trailer",
          "isPremier",
          "startDate",
          "endDate",
          "isActive"
        ],
        "properties": {
          "_id": {
            "type": "string",
            "format": "objectId"
          },
          "title": {
            "type": "string"
          },
          "tagLine": {
            "type": "string"
          },
          "overview": {
            "type": "string"
          },
          "year": {
            "type": "int",
            "format": "YYYY"
          },
          "certification": {
            "type": "string"
          },
          "releaseDate": {
            "type": "string",
            "format": "YYYY-MM-DD"
          },
          "genres": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "objectId"
            }
          },
          "runtime": {
            "type": "string",
            "format": "2h 30m"
          },
          "imdbScore": {
            "type": "int",
            "format": "7.3"
          },
          "rottenTomatoes": {
            "type": "string",
            "format": "82%"
          },
          "fandangoAudienceScore": {
            "type": "string",
            "format": "86%"
          },
          "image": {
            "type": "string",
            "format": "url"
          },
          "trailer": {
            "type": "string",
            "format": "url"
          },
          "isPremier": {
            "type": "boolean"
          },
          "startDate": {
            "type": "string",
            "format": "YYYY-MM-DD"
          },
          "endDate": {
            "type": "string",
            "format": "YYYY-MM-DD"
          },
          "isActive": {
            "type": "boolean"
          }
        }
      },
      "Genres": {
        "type": "object",
        "required": ["id", "genre"],
        "properties": {
          "_id": {
            "type": "string",
            "format": "objectId"
          },
          "genre": {
            "type": "string"
          }
        }
      }
    }
  },
  "security": [
    {
      "ApiKeyAuth": []
    }
  ],
  "tags": [
    {
      "name": "Users"
    },
    {
      "name": "Movies"
    },
    {
      "name": "Genres"
    }
  ],
  "externalDocs": {
    "description": "Find more info here",
    "url": "https://docs.example.com"
  }
}
